name: "collective.catalogtrace CI"

on:
  push:

env:
  python-version: "3.12"
  plone-version: "6.1.3"

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ env.python-version }}
      plone-version: ${{ env.plone-version }}
    steps:
      - name: Test vars
        run: |
          echo 'python-version=${{ env.python-version }}'
          echo 'plone-version=${{ env.plone-version }}'

  lint:
    name: "Backend: Lint"
    needs:
      - config
    uses: plone/meta/.github/workflows/backend-lint.yml@2.x
    with:
      python-version: ${{ needs.config.outputs.python-version }}
      plone-version: ${{ needs.config.outputs.plone-version }}
